# Define workflow name.
name: Build MatrixOne

on:
  workflow_dispatch:
  schedule:
    - cron: '10 */1 * * *'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    name: Build on CentOS/x64

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it.
      - uses: actions/checkout@v2
        with:
          fetch-depth: '3'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18


      - name: Build Configure
        run: |
          cd $GITHUB_WORKSPACE && make clean && make config


      - name: Unit Testing
        run: |
          make ut SKIP_TEST="race"
